### ISSUE TITLE
Database missing

### ISSUE THREAD

**Issue by csteeg** [farm-army/farm-army-frontend#5]
The database initialization file for the front end project is missing. Backend has a sql file, but the PHP frontend doesn't

When starting the frontend I get:
An exception occurred while executing 'SELECT f0_.id AS id_0, f0_.hash AS hash_1, f0_.farm_id AS farm_id_2, f0_.name AS name_3, f0_.tvl AS tvl_4, f0_.json AS json_5, f0_.created_at AS created_at_6, f0_.updated_at AS updated_at_7, f0_.last_found_at AS last_found_at_8, f0_.token AS token_9, f0_.chain AS chain_10, f0_.leverage AS leverage_11, f0_.compound AS compound_12, f0_.token0 AS token0_13, f0_.token1 AS token1_14 FROM farm f0_ ORDER BY f0_.created_at DESC LIMIT 20':

**Comment by csteeg** [comment]
Symfony-n00b here, found that you can do migrations on https://symfony.com/doc/current/doctrine.html#migrations-creating-the-database-tables-schema

php bin/console make:migration
php bin/console doctrine:migrations:migrate

**Comment by Haehnchen** [comment]
readme updated: https://github.com/farm-army/farm-army-frontend#install
