### ISSUE TITLE
"Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait"　Error

### ISSUE THREAD

**Issue by RootA** [farm-army/farm-army-frontend#6]
[PHP-FPM    ] [12-Jan-2022 07:06:45 UTC] 2022-01-12T07:06:45+00:00 [critical] Uncaught Exception: "App\Kernel" uses "Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait", but does not implement the required method "protected function configureContainer(ContainerConfigurator $c): void".

**Comment by Haehnchen** [comment]
you have now the latest file with last sync
